steps:
  - label: "Test docker (vendored)"
    plugins:
      - "./.buildkite/plugins/docker":
          image: "hello-world"

  - label: "Test clowns (submodule)"
    plugins:
      - "./.buildkite/plugins/detect-clowns": ~

